#!/bin/bash
##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=WRFmg.job       #Set the job name to "JobExample3"
#SBATCH --time=12:00:00            #Set the wall clock limit to 1 Day and 12hr
#SBATCH --ntasks=8                 #Request 8 tasks
#SBATCH --ntasks-per-node=8          #Request 2 tasks/cores per node
#SBATCH --mem=300G                  #Request 4096MB (4GB) per node
#SBATCH --output=WRFmg.%j      #Send stdout/err to "Example3Out.[jobID]"
#SBATCH --mail-type=ALL       #Send email on all events
#SBATCH --mail-user=rpkamakura@tamu.edu  #send email to me

cd $SCRATCH/LIBRARIES/WPS
module purge
module load GCC/11.3.0 OpenMPI/4.1.4 WPS/4.4-dmpar
module load netCDF/4.9.0
module load foss/2022a

export HDF5=$EBROOTHDF5
export NETCDF=$EBROOTNETCDF
export NETCDF_classic=1
export WRF_DIR=$SCRATCH/LIBRARIES/WRFV4.6.0
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

mpirun ./metgrid.exe
