#!/bin/bash
##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=WRFrl.job       #Set the job name to "JobExample3"
#SBATCH --time=2:00:00            #Set the wall clock limit to 1 Day and 12hr
#SBATCH --ntasks=80                 #Request 8 tasks
#SBATCH --ntasks-per-node=20          #Request 2 tasks/cores per node
#SBATCH --mem=360G                  #Request 4096MB (4GB) per node
#SBATCH --output=WRFrl.%j      #Send stdout/err to "Example3Out.[jobID]"
#SBATCH --mail-type=ALL         #send email on all events
#SBATCH --mail-user=rpkamakura@tamu.edu   #send email to Ren Kamakura

#&domains
 #nproc_x = 10
 #nproc_y = 8
#/

cd $SCRATCH/LIBRARIES/WRFV4.6.0/run
module purge
module load foss/2022a
module load GCCcore/11.3.0 bzip2/1.0.8
module load netCDF-combined/4.9.3-gompi-2022a PnetCDF/1.12.3
export I_MPI_PMI_LIBRARY=usr/lib64/libmpi.so
export NETCDF=$EBROOTNETCDFCOMBINED
export HDF5=$EBROOTHDF5
export NETCDF_classic=1

mpirun ./real.exe
