#!/bin/bash
##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=WRFungrib.job       #Set the job name to "JobExample3"
#SBATCH --time=12:00:00            #Set the wall clock limit to 1 Day and 12hr
#SBATCH --ntasks=8                 #Request 8 tasks
#SBATCH --ntasks-per-node=8          #Request 2 tasks/cores per node
#SBATCH --mem=300G                  #Request 4096MB (4GB) per node
#SBATCH --output=WRFub.%j      #Send stdout/err to "Example3Out.[jobID]"
#SBATCH --mail-type=ALL       #Send email on all events
#SBATCH --mail-user=rpkamakura@tamu.edu  #send email to me

cd $SCRATCH/LIBRARIES/WPS
module purge
module load iccifort/2019.5.281  impi/2018.5.288  WPS/4.1-dmpar
#export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
./link_grib.csh ../ERA5/SFC/*.grib

./ungrib.exe
