#!/bin/bash
##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=WRFcomp.job       #Set the job name to "JobExample3"
#SBATCH --time=2:00:00            #Set the wall clock limit to 1 Day and 12hr
#SBATCH --ntasks=8                 #Request 8 tasks
#SBATCH --ntasks-per-node=2          #Request 2 tasks/cores per node
#SBATCH --mem=20G                  #Request 4096MB (4GB) per node
#SBATCH --output=WRFcomp.%j      #Send stdout/err to "Example3Out.[jobID]"
#SBATCH --mail-type=ALL         #send email on all events
#SBATCH --mail-user=rpkamakura@tamu.edu   #send email to Ren Kamakura

cd $SCRATCH/LIBRARIES/WRF

module purge
module load foss/2020a
module load netCDF-combined/4.7.4-gompi-2020a PnetCDF/1.12.1
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export NETCDF=$EBROOTNETCDF
export HDF5=$EBROOTHDF5
export NETCDF_classic=1

./compile em_real >& log.compile
