#!/bin/bash
##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=WRFcomp.job       #Set the job name to "WRFcomp"
#SBATCH --time=2:00:00            #Set the wall clock limit to 2 hrs
#SBATCH --ntasks=8                 #Request 8 tasks
#SBATCH --ntasks-per-node=2          #Request 2 tasks/cores per node
#SBATCH --mem=20G                  #Request 20G per node
#SBATCH --output=WRFcomp.%j      #Send stdout/err to "WRFcomp.[jobID]"
#SBATCH --mail-type=ALL         #send email on all events
#SBATCH --mail-user=rpkamakura@tamu.edu   #send email to Ren Kamakura

cd $SCRATCH/MHW_WRF/WRF

module purge
module load foss/2024a
module load GCCcore/14.2.0 bzip2/1.0.8
module load netCDF-combined/4.9.3-gompi-2023a PnetCDF/1.12.3
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export NETCDF=$EBROOTNETCDF
export HDF5=$EBROOTHDF5
export NETCDF_classic=1

./compile em_real >& log.compile
